### ISSUE TITLE
Highlighting not working

### ISSUE THREAD

**Issue by tim-hilt** [synaptiko/xit.nvim#5]
I have installed the plugin according to the README. I also got the notification, that the TS-grammar for xit is being installed. However, I don't see any syntax-highlighting when opening an xit-file.

I also tried with `disable_default_highlight = true`, which got me the same result.

Any idea, why this could be happening? You can take a look at my setup [here](https://github.com/tim-hilt/nvim/blob/main/lua/tim/plugins.lua#L308-L322)

**Comment by felipesere** [comment]
Yeah, I have the same issue.

**Comment by synaptiko** [comment]
Should be fixed now.

**Comment by foolishprogrammer** [comment]
> Should be fixed now.

I think it still not working..? I have update the language treesitter, yet I found this on on `:checkhealth`

```
- ERROR xit(highlights): /usr/share/nvim/runtime/lua/vim/treesitter/query.lua:259: query: invalid node type at position 177 for language xit
  xit(highlights) is concatenated from the following files:
  | [ERROR]:"/home/regalos/.local/share/nvim/lazy/xit.nvim/queries/xit/highlights.scm", failed to load: /usr/share/nvim/runtime/lua/vim/treesitter/query.lua:259: query: invalid node type at position 177 for language xit
```

**Comment by synaptiko** [comment]
@foolishprogrammer I'm sorry about it. Unfortunately I don't have much time lately and I also stopped using Neovim myself (although I'd love to get back to it, once I have more time again).

If there is anyone willing to continue maintaining this project, I'd be happy to give them permissions for that. Maybe @felipesere would be interested?

**Comment by foolishprogrammer** [comment]
> @foolishprogrammer I'm sorry about it. Unfortunately I don't have much time lately and I also stopped using Neovim myself (although I'd love to get back to it, once I have more time again).

Somehow I found the plugin now working.... Why? Don't exactly know. No plugin update, no system update.

> If there is anyone willing to continue maintaining this project, I'd be happy to give them permissions for that. Maybe @felipesere would be interested?

I would love to contribute as I use xit a lot, but not right now. After I get a new job and have more free time, would love to work and help with this project.

**Comment by synaptiko** [comment]
@foolishprogrammer Great, then once you have some bandwidth, let me know here and we can arrange something. In the meantime you can think of what could be improved.
